version: '3.1'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      target: dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php-fpm
    restart: on-failure
    user: ${PHP_OWNER}
    volumes:
      - .:/var/www/html

  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:/var/www/html

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    restart: on-failure
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

volumes:
  database:
    driver: local
  database_test:
    driver: local