version: '3.1'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      target: dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php-fpm
    restart: on-failure
    user: ${PHP_OWNER}
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - .:/var/www/html
    command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'

  nginx:
    image: mmierzynski/nginx:1.20
    container_name: nginx
    restart: on-failure
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    restart: on-failure
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  redis:
    image: redis:7.0
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


volumes:
  database:
    driver: local
  database_test:
    driver: local